user_name_max_length: 50
user_email_max_length: 255
user_password_min_length: 6
user_per_page: 8

session_remember_user: 1

subject_per_page: 8
subject_name_max_length: 50
subject_description_max_length: 100

question_content_max_length: 255

answer_content_max_length: 255

exam_limited_time_min: 5
exam_limited_time_max: 1000
